locusta-frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend

    container_name: locusta-frontend

    ports:
      - "3000:80"

    depends_on:
      - locusta-c2

    restart: unless-stopped

    networks:
      - hive-network